# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  gtk3-nocsd = {
    pname = "gtk3-nocsd";
    version = "512c2bd866d71def6ffd4d85ca98ae12fe989c62";
    src = fetchFromGitHub {
      owner = "ZaWertun";
      repo = "gtk3-nocsd";
      rev = "512c2bd866d71def6ffd4d85ca98ae12fe989c62";
      fetchSubmodules = false;
      sha256 = "sha256-BOsQqxaVdC5O6EnB3KZinKSj0U5mCcX8HSjRmSBUFks=";
    };
    date = "2021-06-23";
  };
  lightly-shaders = {
    pname = "lightly-shaders";
    version = "cea07c0996373e3a0eaf232f478ebff7a913af8f";
    src = fetchFromGitHub {
      owner = "a-parhom";
      repo = "LightlyShaders";
      rev = "cea07c0996373e3a0eaf232f478ebff7a913af8f";
      fetchSubmodules = false;
      sha256 = "sha256-l6UXgU2Xv57Ge9fO6tk5a6+mPG7zrxdm28FAOSRZnA4=";
    };
    date = "2023-03-29";
  };
  manix = {
    pname = "manix";
    version = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
    src = fetchFromGitHub {
      owner = "mlvzk";
      repo = "manix";
      rev = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
      fetchSubmodules = false;
      sha256 = "sha256-GqPuYscLhkR5E2HnSFV4R48hCWvtM3C++3zlJhiK/aw=";
    };
    date = "2021-04-20";
  };
  mpv-iptvplus = {
    pname = "mpv-iptvplus";
    version = "e4fde04bbad4573b94695df6409edf6e88ecdb3c";
    src = fetchFromGitHub {
      owner = "pintassilgo";
      repo = "mpv-iptvplus";
      rev = "e4fde04bbad4573b94695df6409edf6e88ecdb3c";
      fetchSubmodules = false;
      sha256 = "sha256-+LTp2eTVow+ib0/+8YZkxZ+X4LI8bFxT/i05XeEFBx8=";
    };
    date = "2023-01-04";
  };
  plasma5-applets-window-appmenu = {
    pname = "plasma5-applets-window-appmenu";
    version = "1de99c93b0004b80898081a1acfd1e0be807326a";
    src = fetchFromGitHub {
      owner = "psifidotos";
      repo = "applet-window-appmenu";
      rev = "1de99c93b0004b80898081a1acfd1e0be807326a";
      fetchSubmodules = false;
      sha256 = "sha256-PLlZ2qgdge8o1mZOiPOXSmTQv1r34IUmWTmYFGEzNTI=";
    };
    date = "2022-06-27";
  };
  swhkd = {
    pname = "swhkd";
    version = "30f25b5bf99df5f16d91b51a7bd397c1de075085";
    src = fetchFromGitHub {
      owner = "waycrate";
      repo = "swhkd";
      rev = "30f25b5bf99df5f16d91b51a7bd397c1de075085";
      fetchSubmodules = false;
      sha256 = "sha256-K05v2xw7G/ZJsf62g696TOSZHMAOWf24sT9JcvvBNx0=";
    };
    date = "2023-10-16";
  };
  wallpaper-engine-kde-plugin = {
    pname = "wallpaper-engine-kde-plugin";
    version = "08dad16f5cbf0de423b85edda313597c273a887e";
    src = fetchFromGitHub {
      owner = "catsout";
      repo = "wallpaper-engine-kde-plugin";
      rev = "08dad16f5cbf0de423b85edda313597c273a887e";
      fetchSubmodules = true;
      sha256 = "sha256-rrBsQy+vG22IiaNDHYbkNPPbExQPQYLCaXy+KMHDmss=";
    };
    date = "2023-10-22";
  };
}
